version: '3'
services:
  db:
    image: mariadb
    container_name: gostack-mysql
    volumes:
        - "./volumes/data/.mysql:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
        - "33080:3306"
  mongo:
    image: mongo
    container_name: gostack-mongodb
    volumes:
        - "./volumes/data/.mongo:/data/db"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    ports:
        - "27017:27017"
